POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {token}

{
  "name": "Samsung A18",
  "description": "Samsung A18",
  "price": 100000,
  "quantity": 2,
  "isAvailable": true,
  "category": ["electronics"],
  "condition": "used",
  "region": "Nigeria"
}
