PATCH http://localhost:3000/password-management/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMG0xbjV1cG14emtyYnhydDdqMHZoc3MiLCJlbWFpbCI6ImpvaG5raW5nMUBnbWFpbC5jb20iLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3NDczODE5ODYsImV4cCI6MTc0NzM4NTU4NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.S2I1bKquNi8-LHXIOBmHbTBG5xdO_WN8LBLtYrtyzZs


{
  "password": "Testing109%!"
}