GET http://localhost:3000/delivery/view/trackingIdentifier/EVDD - 2260
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aGtjcnFjcWhpOGh4dTZiMmQzNGpteW8iLCJlbWFpbCI6ImpvaG5raW5nMTIzNEBnbWFpbC5jb20iLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE3NDk5NDE4NDUsImV4cCI6MTc0OTk0NTQ0NSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.f0HL1SQqV9fTnGpxKiGT6Ol-McEH_EDpNJA5Tp3iFX8